version: 2
updates:
  - package-ecosystem: "github-actions" # See documentation for possible values
    target-branch: "unstable"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    
