from typing import List

class Converter:
    _obj1: object
    _obj2: object
    def __init__(self, __obj1: object, __obj2: object) -> None: ...
    def __repr__(self) -> str: ...
    def _map_attr(self) -> dict: ...
    def get_attr(self, attr: str) -> str: ...
    def get_attrs(self) -> List[str]: ...
    @property
    def ref(self) -> object: ...
    @property
    def diff(self) -> List[dict]: ...
