from enum import Enum

class ErrorType(str, Enum): ...

class IncorrectAlphanumeric(Exception):
    def __init__(self): ...

class MissingNumeric(Exception):
    def __init__(self): ...

class TooManyAuthors(Exception):
    def __init__(self): ...

class UnknownService(Exception):
    def __init__(self): ...
