from enum import Enum

class ErrorType(str, Enum): ...

class IncorrectAlphanumericError(Exception):
    def __init__(self): ...

class MissingNumericError(Exception):
    def __init__(self): ...

class TooManyAuthorsError(Exception):
    def __init__(self): ...
