import datetime
from io import FileIO, IOBase
from logging import Logger
from typing import Optional, Union

from interactions.api.models.attrs_utils import DictSerializerMixin, define

log: Logger

@define()
class Overwrite(DictSerializerMixin):
    id: int
    type: int
    allow: str
    deny: str

@define()
class ClientStatus(DictSerializerMixin):
    dektop: Optional[str]
    mobile: Optional[str]
    web: Optional[str]

class Snowflake:
    def __init__(self, snowflake: Union[int, str, "Snowflake"]) -> None: ...
    def __int__(self): ...
    @property
    def increment(self) -> int: ...
    @property
    def worker_id(self) -> int: ...
    @property
    def process_id(self) -> int: ...
    @property
    def epoch(self) -> float: ...
    @property
    def timestamp(self) -> datetime.datetime: ...
    def __hash__(self): ...
    def __eq__(self, other): ...

class Color:
    @property
    def blurple(self) -> hex: ...
    @property
    def green(self) -> hex: ...
    @property
    def yellow(self) -> hex: ...
    @property
    def fuchsia(self) -> hex: ...
    @property
    def red(self) -> hex: ...
    @property
    def white(self) -> hex: ...
    @property
    def black(self) -> hex: ...

class File:
    def __init__(
        self, filename: str, fp: Optional[IOBase] = ..., description: Optional[str] = ...
    ) -> None: ...

class Image:
    def __init__(self, file: Union[str, FileIO], fp: Optional[IOBase] = ...) -> None: ...
    @property
    def data(self) -> str: ...
    @property
    def filename(self) -> str: ...
